### ISSUE TITLE
how can we ensure each job is consumed at least once?

### ISSUE THREAD

**Issue by mxchenxiaodong** [rails/solid_queue#194]
## question
I'm currently learning the solid queue design, which I find very clean and enjoyable to read.

I have a question around handling jobs after they transition from ReadyExecution to ClaimedExecution. If the entire process crashes unexpectedly (not a graceful shutdown), how are the jobs already in the ClaimedExecution state handled? Currently it doesn't seem there is logic to cover this case.

My question is: if these claimed jobs are not handled, how can we ensure each job is consumed at least once?

## this code
lib/solid_queue/worker.rb: 
```
def poll
  claim_executions.then do |executions|
    executions.each do |execution|
      pool.post(execution)
    end

    executions.size
  end
end

def claim_executions
  with_polling_volume do
    SolidQueue::ReadyExecution.claim(queues, pool.idle_threads, process.id)
  end
end
```

I would appreciate any clarification on this matter.Thank you!

**Comment by rosa** [comment]
Hey @mxchenxiaodong, thank you! [There's a brief explanation about this in the README](https://github.com/basecamp/solid_queue?tab=readme-ov-file#threads-processes-and-signals):

> If processes have no chance of cleaning up before exiting (e.g. if someone pulls a cable somewhere), in-flight jobs might remain claimed by the processes executing them. Processes send heartbeats, and the supervisor checks and prunes processes with expired heartbeats, which will release any claimed jobs back to their queues. You can configure both the frequency of heartbeats and the threshold to consider a process dead. See the section below for this. 

When you start a new supervisor, or simply periodically, the supervisor checks for processes that have died and deregister them. Deregistering a process releases its claimed executions. Also, claimed executions have [their own `release` method](https://github.com/basecamp/solid_queue/blob/d71aa8ad6dd435fc458fc07be5ecc3b0cf4e89de/app/models/solid_queue/claimed_execution.rb#L48-L53). Yours doesn't work because the job is already in the system and you can't just enqueue it again.

**Comment by mxchenxiaodong** [comment]
I understand now, thank you for the explanation~


app/models/solid_queue/process.rb
```ruby
class SolidQueue::Process < SolidQueue::Record
  after_destroy -> { claimed_executions.release_all }
end
```

😆
