### ISSUE TITLE
Store actual exception instead of full `retry_on` condition

### ISSUE THREAD

**Issue by matteeyah** [rails/solid_queue#249]
## Summary

When a job fails SolidQueue stores the exception that caused the job to fail. e.g.

```json
    "exception_executions": {
      "[CustomError, JSON::ParserError]": 4
    },
```

The relevant `retry_on` statement looks like this:

```ruby
  class CustomError < StandardError; end

  retry_on CustomError, JSON::ParserError do |job, error|
    Rails.logger.error(error.message)
  end
```

However, the stored exception shows the full `retry_on` condition, instead of the actual error. In this scenario, we don't know if the job failed because of `CustomError` or `JSON::ParserError`.

## Proposal

Store the actual exception that caused the job to fail, instead of the `retry_on` condition that caught it.

**Comment by rosa** [comment]
Huh, these are part of the serialized active job, and are used only by Active Job, not Solid Queue 🤔  I think [this is expected](https://github.com/rails/rails/blob/de4d8744744acab2dd9db0683ccf784ea45810b2/activejob/lib/active_job/exceptions.rb#L187-L189) since these are used to track how many attempts were made for that specific `retry_on`, so you can have something like: 
```ruby
retry_on CustomError, JSON::ParserError, attempts: 10
retry_on AnotherCustomError, attempts: 3
```
and each one would be tracked and checked against `attempts` separately. It was added in https://github.com/rails/rails/pull/34352. 

Closing as this is not Solid Queue related. Thank you!

**Comment by matteeyah** [comment]
Ahh, that makes sense. Thanks for responding so fast.
