### ISSUE TITLE
Deleting scheduled jobs

### ISSUE THREAD

**Issue by JuzerShakir** [rails/solid_queue#254]
Hi! I have a Rails app that allows users to sign up and add a list of friends or loved ones with their birthdays. The app will then email the user on their loved ones' birthdays (reminder).

To achieve this I am using Action Mailer (to send emails) and Active Job (for delivering at specified date & time) and the background job adapter I am using is the `solid_queue`.

I have successfully implemented this in both the development & production environments. The emails are sent to the user at midnight of their preferred time zone selected when the user created the account.

The solid queue enqueues the job whenever the user creates or updates the `birthdate` field. So, let's say I create a reminder birthday of a loved one, it triggers the solid queue and schedules it to be delivered later on their birthday. 

But now, the problem is that when the user updates an existing `birthdate` field for any loved one, the solid queue will trigger again and create a new scheduled job to send an email on the updated birthday. So now we have 2 scheduled jobs in the db for a single birthday. (1st created at create and 2nd was created at update). And now 2 emails will be sent for a single loved one's birthday on different dates which is not what we want.

So the only solution I can think of currently is that when the birthdate field is updated, we need to delete an existing job first and create another scheduled job for the updated birthdate.

But how should I, or putting it this way, what's the best way to query the solid queue db for a particular instance and delete it from the scheduled jobs?

Or is there a much better way that the Solid Queue offers that I am not aware of? 

Any ideas or thoughts would be appreciated! :)

**Comment by rosa** [comment]
Hey @JuzerShakir, this seems to be an app/domain-specific question, rather than a Solid Queue question 🤔 All the Active Job backends will behave in the same way if they support scheduled jobs. 

My suggestion in this case would be to handle this scenario in the job so that when the job runs, it checks whether it needs to send an email or not (i.e. the birthday date matches the current day, if that's the goal), instead of blindly sending it. Another solution, instead of using scheduled jobs for this, would be to have a recurring (cron-style) job that checks all birthdays that it needs to notify about every day (handling time zones in the way you're currently handling them) and enqueued jobs to send the notifications to be run right away.
