### ISSUE TITLE
Execute polling queries to ReadReplica

### ISSUE THREAD

**Issue by tmimura39** [rails/solid_queue#275]
Hello, Thank you very much for the very nice Gem 👍 

I have started to consider using it in my company.

So I would like to discuss one point with you.

Currently SolidQueue performs a large number of polling queries to writing, its default connection destination.
We believe that polling queries should be issued against lead replicas.

It is very simple but can be implemented as follows.
```ruby
diff --git a/lib/solid_queue/processes/poller.rb b/lib/solid_queue/processes/poller.rb
index 193ae5b..0087c27 100644
--- a/lib/solid_queue/processes/poller.rb
+++ b/lib/solid_queue/processes/poller.rb
@@ -43,10 +43,12 @@ def shutdown
       end

       def with_polling_volume
-        if SolidQueue.silence_polling? && ActiveRecord::Base.logger
-          ActiveRecord::Base.logger.silence { yield }
-        else
-          yield
+        ApplicationRecord.connected_to(role: :reading) do
+          if SolidQueue.silence_polling? && ActiveRecord::Base.logger
+            ActiveRecord::Base.logger.silence { yield }
+          else
+            yield
+          end
         end
       end
   end
```

It would be nice if this part could be customized since not all users hold ReadReplica.

how do you like it?

**Comment by rosa** [comment]
Hi @tmimura39! Thanks a lot for considering using this gem 🙏 

I think the problem of connecting to a read replica to run the polling queries is that the polling queries are locking reads of the `SELECT ... FOR UPDATE` kind to lock the found rows and prevent other workers from grabbing them. We could issue non-locking reads to see if there are records at all and then switch to the primary to do the locking reads, but that would be slower and depending on your job volume, might not be worth it because polling queries always find work to do 🤔 Also, in the case of not finding work, the queries should be quite light and fast. 

Are you having problems with these queries against your primary?

**Comment by tmimura39** [comment]
Hi @rosa , Thanks for the response!

Oh, I hadn't thought that far ahead.

> Are you having problems with these queries against your primary?

Nope, no problems so far, just a little load on Primary's CPU.

Thank you for your detailed explanation.

I understand the situation 👍
