### ISSUE TITLE
Errno::ECHILD: No child processes error when starting SolidQueue with rake solid_queue:start

### ISSUE THREAD

**Issue by BrijeshSajeev** [rails/solid_queue#298]
When attempting to start SolidQueue using bundle exec rake solid_queue:start, an Errno::ECHILD: No child processes error is raised. The error occurs during the waitpid2 system call within the reap_and_replace_terminated_forks method in the fork_supervisor.rb file. This seems to indicate an issue with handling child processes in the forking supervisor.

## Environment
-     Ruby Version: 3.1.6
-     Rails Version: 7.1.0
-     SolidQueue Version: 0.5.0
-     RVM/Gemset: ruby-3.1.6@rg_rails_7-rb-3.1.6

**Comment by BrijeshSajeev** [comment]
![Screenshot from 2024-08-24 18-23-54](https://github.com/user-attachments/assets/c5638472-eadc-4beb-bfac-6adcdf9c87e5)

**Comment by rosa** [comment]
Huh, this is very strange. Could you share a bit more about your setup? Or the full log since it starts until it triggers that error? At that point it should have forked some process so there should be at least a child process... I wonder if there's no configuration at all and no forks are being created... I might not be handling this case well 🤔

**Comment by BrijeshSajeev** [comment]
![image](https://github.com/user-attachments/assets/7062eaf7-a3fe-430a-94b4-c00eaf7b2a49)
### Set Up :
- OS: Ubuntu 22.04.4 LTS x86_64
- Ruby Version: 3.1.6
- Rails Version: 7.1.0
- SolidQueue Version: 0.5.0

**Comment by rosa** [comment]
And could you share your solid queue configuration as well?

**Comment by BrijeshSajeev** [comment]
sure 
production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
      # recurring_tasks:
      #   mat_company_activity:
      #     class: Cron::MatCompanyActivityJob
      #     schedule: every 1 hour
  workers:
    - queues: "*"
      threads: 3
      polling_interval: 2
    - queues: [ real_time, background ]
      threads: 5
      polling_interval: 0.1
      processes: 3

**Comment by rosa** [comment]
Thanks! And are you testing this in `development` environment? Or production?

**Comment by BrijeshSajeev** [comment]
i'm testing this in dev, but somehow it takes the config for production

**Comment by BrijeshSajeev** [comment]
![image](https://github.com/user-attachments/assets/5d6e3366-3121-4fbb-b8e6-a71a09e09e63)
![image](https://github.com/user-attachments/assets/6f6690bf-d997-4082-ad76-d95f655badc1)

**Comment by rosa** [comment]
Ok, so when you added the configuration in `development` above, you stopped getting the `Errno::ECHILD` error, right? This is something I need to handle better, when you don't have any workers or dispatchers configured at all 🤔 I'll fix that to finish gracefully, and to use the default configuration if the file is present but doesn't have any configuration for the given environment. 

Now, to the second issue: 
> When I run bundle exec rake solid_queue:start, it appears to be doing nothing—no logs, no errors, no noticeable activity. The process seems to hang without any feedback. 

By default it'll use `Rails.logger` to log, so you might have to check `log/development.log` to see if it's logging anything. Otherwise, you could add this to your `development.rb` environment: 
```ruby
config.solid_queue.logger = ActiveSupport::Logger.new(STDOUT)
```
And see if that shows the workers and dispatcher starting and running.

**Comment by BrijeshSajeev** [comment]
yeah, it's working now 
![image](https://github.com/user-attachments/assets/62a5c896-6514-4aef-857a-ff92c7242945)
but something is wrong with my server
![image](https://github.com/user-attachments/assets/fec623e0-8d74-4308-9bea-516b5b549802)

**Comment by rosa** [comment]
Hmm yes... that one is new to me... Maybe [this helps](https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total)?

**Comment by BrijeshSajeev** [comment]
It's working fine.
Thank you so much for your quick response and for helping me out with this issue. I really appreciate your time and great talk.

**Comment by rosa** [comment]
Nice! 👏 So glad to hear it's working! I'll ship an improvement for the configuration problem and the `Errno::ECHILD` error when the configuration is empty.
