### ISSUE TITLE
For deleted recurring_tasks

### ISSUE THREAD

**Issue by tmimura39** [rails/solid_queue#310]
Hi, Let me ask you a question about https://github.com/rails/solid_queue/pull/272.

This support is very convenient as it allows recurring_tasks to be checked in MissionControl.　thanks 👍 

However, there seems to be a problem with “recurring_tasks deleted from the YAML configuration file” that continue to remain on the MissionControl dashboard.

This is because we only process `create or update` for `SolidQueue::RecurringTask`.
https://github.com/rails/solid_queue/blob/7901a8e786de79daf4f35861b1393503bd7000b2/lib/solid_queue/dispatcher/recurring_schedule.rb#L43-L45

We do not think this is a major issue since the task does not continue to run, just remains on the MissionControl dashboard.
However, as the recurring_task setting is repeatedly added and removed, the MissionControl dashboard becomes polluted.

Is this the intended behavior?

**Comment by rosa** [comment]
Yes, it's intended, for now. The reason is that the current setup allows you to have multiple dispatchers, running different recurring tasks so a single dispatcher can't delete all tasks that aren't in its configuration because they might belong to a different dispatcher with a different configuration. 

I plan to improve this, though, and clean up these old tasks. I have other improvements that I need to implement for recurring tasks, so I'll do all those together.

**Comment by tmimura39** [comment]
Thanks for the reply!

Yes, I agree. I didn't think it would be easy.

I'm looking forward to seeing more improvements in the future!
