### ISSUE TITLE
unable to retry on SolidQueue::ProcessExitError

### ISSUE THREAD

**Issue by InteNs** [rails/solid_queue#313]
hello again!

After updating to V0.6 we naturally started getting failed jobs with `SolidQueue::ProcessExitError` as the error causing the job to fail.

This looked like a perfect candidate of an exception that we should always retry so i tried adding the following to ApplicationJob:
```ruby
retry_on SolidQueue::ProcessExitError, wait: :polynomially_longer, attempts: 5
```

unfortunately it seems that this error class is not known to the application:
```
app/jobs/application_job.rb:16:in `<class:ApplicationJob>': uninitialized constant SolidQueue::ProcessExitError (NameError)

           SolidQueue::ProcessExitError,
                     ^^^^^^^^^^^^^^^^^^
Did you mean?  SolidQueue::Processes
	from app/jobs/application_job.rb:1:in `<top (required)>'
```

any ideas as to why this class is not loaded in the rails app?

maybe because the supervisor is loaded in another process (docker container in my case) and not the server process where jobs are actually scheduled?

**Comment by rosa** [comment]
Ohhh, yes! Agh, my fault. The `SolidQueue::ProcessExitError` [is not set up properly in a way that Zeitwerk can load it](https://github.com/fxn/zeitwerk?tab=readme-ov-file#the-idea-file-paths-match-constant-paths). It's loaded for Solid Queue because the file is loaded anyway before forking, but that won't be the case where you enqueue the job. 

I'll fix it and will release a new version with the fix shortly.
