### ISSUE TITLE
Is there a way to exclude queues for workers?

### ISSUE THREAD

**Issue by salmonsteak1** [rails/solid_queue#392]
Hey, I'm looking to segregate my workers for specific jobs so that long running jobs wouldn't hog up my main set of workers working on the '\*' queue. Is that possible? Currently it seems like what I've defined below would cause the set of workers defined with '\*' to work on `SpecificLongRunningJob` too:

```ruby
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: '*'
      threads: 1
      processes: 3
      polling_interval: 0.1
    - queues: 'SpecificLongRunningJob'
      threads: 1
      processes: 3
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

**Comment by rosa** [comment]
Yes, that's right. There's no way to exclude queues from workers. `*` means all queues, including `SpecificLongRunningJob`. You'd have to explicitly list all queues except for `SpecificLongRunningJob` to achieve that result.

**Comment by coorasse** [comment]
Please note that this might lead to issues when a new queue is introduced, because it might be surprising that jobs from that queue don't get consumed. I liked the GoodJob option to define `-queue_name`, so in this case: `queues: "-SpecificLongRunningJob;*"`. This made it easy to introduce new queues in my app. Maybe is worth considering as a feature?
