### ISSUE TITLE
solid_queue:install doesn't take config.active_record.pluralize_table_names in consideration

### ISSUE THREAD

**Issue by dviana19** [rails/solid_queue#396]
Hi,

I normally use this configuration `config.active_record.pluralize_table_names = false`, which brings me to this issue. I've upgraded an application to Rails 8 to use Solid Queue. However, when I run the command `solid_queue:install`, it just copies the [template](https://github.com/rails/solid_queue/blob/main/lib/generators/solid_queue/install/templates/db/queue_schema.rb) with the table names in the plural.

But in development, Solid Queue uses async so I only found out the issue in production when I got **"could not find the table solid_queue_blocked_executions..."**

Of course, it's an easy fix by just changing the name to singular inside of queue_schema.rb, but I'm wondering if this could be done already in the generator.

**Comment by rosa** [comment]
Oh yes! This came up in https://github.com/rails/solid_queue/pull/354 and, in Rails too, as Active Storage or Action Mailbox behave in the same way: https://github.com/rails/rails/pull/52970#discussion_r1770733592. I think for now this should be documented instead of handling it explicitly, just like it was suggested over in that Rails PR.

**Comment by dviana19** [comment]
Thank you, @rosa. I'll close this issue.
